

class PetHome(object):

    def __init__(self, username: str, password: str, addr: str, port: str):
        self.addr = addr
        self.port = port
        self.protocol = 'http'
        if username is not None and password is not None:
            self.token = self.auth(username, password)

    def auth(self, username: str, password: str) -> str: ...

    def create_ad(self, data: dict) -> int: ...

    def delete_ad(self, id: int): ...

    def get_own_advertisements(self, page: int) -> list: ...

    def get_other_advertisements(self, page: int) -> list: ...

    def get_advertisement_by(self, id: int) -> dict: ...

    def _get_advertisements(self, pov: str, page: int, size: int = 4) -> list: ...

    def get_account(self) -> dict: ...

    def update_account(self, data: dict) -> int: ...

    def create_account(self, data: dict) -> int: ...
